# Root
root_dir = ""
build_dir = "_internal_generic"
loglevel = "debug"

# Project
clean = true

# Custom
default_lib_type = "DynamicLib"

[toolchain.user]
build = true
test = true

id = "Gcc"
name = "gcc"
asm_compiler = "as"
c_compiler = "gcc"
cpp_compiler = "g++"
archiver = "ar"
linker = "ld"

# id = "Msvc"
# name = "msvc"
# asm_compiler = "cl"
# c_compiler = "cl"
# cpp_compiler = "cl"
# archiver = "lib"
# linker = "link"
