root_dir=".."
build_dir="../_build_buildexe_tpl"

loglevel="trace"
clean=false

# TODO, verification

# TODO,
# mode = "script"
# mode = "immediate"

# Target information
name = "libtpl_win"
type = "staticLibrary"
relative_to_root = "third_party/tiny-process-library"
srcs = ["process.cpp", "process_win.cpp"]
includes = [""]

# GCC
# cpp_compile_flags = "-std=c++11", -Wall, -Wextra

# MSVC

