root_dir = ".."
build_dir = "../_build_buildexe_tpl"

loglevel = "trace"
clean = true

# TODO, verification
# [verification]
# os = ["win", "linux"]

# BuildExe run mode
mode = "immediate"
# mode = "script"

# Target information
# [build.info]
name = "libtpl_unix"
type = "staticLibrary"
relative_to_root = "third_party/tiny-process-library"

# [build.inputs]
srcs = ["process.cpp", "process_unix.cpp"]
includes = [""]
common_compile_flags = ["-std=c++17", "-Os"]
cpp_compile_flags = ["-Wall", "-Wextra", "-Werror"]

