# Root
root_dir = ""
build_dir = "_internal_win"
loglevel = "trace"

# Project
clean = true

# Toolchain
[toolchain.gcc]
build = true
test = true

[toolchain.msvc]
build = true
test = true

# Custom toolchain added here
[toolchain.clang_gnu]
build = true
test = true

id = "Clang"
name = "clang_gnu"
asm_compiler = "llvm-as"
c_compiler = "clang"
cpp_compiler = "clang++"
archiver = "llvm-ar"
linker = "ld"

# Custom target added here
[target.clang_gnu]
compile_command = "{compiler} {preprocessor_flags} {include_dirs} {compile_flags} -o {output} -c {input}"
link_command = "{cpp_compiler} {link_flags} {compiled_sources} -o {output} {lib_dirs} {lib_deps}"
