# Root
root_dir = ""
build_dir = "_internal_win"
loglevel = "trace"

# Project
clean = true

# Toolchain
[toolchain.gcc]
build = true
test = true

[toolchain.msvc]
build = true
test = true

# Custom toolchain added here
[toolchain.clang_w64_windows_gnu]
build = true
test = true
